# Site settings
title: Montavilla Neighborhood Association 
email: mail@montavillapdx.org
description: The home of the Montavilla Neighborhood Association
baseurl: "/montavillapdx"
url: "https://montavillapdx.org"

author:
  name     : 'Montavilla Neighborhood Association'
  email    : mail@montavillapdx.org
  url      : https://www.montavillapdx.org
  facebook : https://www.facebook.com/montavillapdx/
  twitter  : http://twitter.com/montavillapdx

github: https://github.com/montavillapdx/montavillapdx.org
disqus_shortname: "montavilla-neighborhood-association"
google_analytics: "UA-109339605-1"

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
